apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-mecanica-config
data:
  APP_ENV: "production"
  APP_URL: "http://oficina-mecanica-api-service"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_DATABASE: "oficina_mecanica"
