apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-secrets
type: Opaque
stringData:
  APP_KEY: ""
  DB_USERNAME: "oficina_user"
  DB_PASSWORD: ""
  DB_DATABASE: "oficina_mecanica"
  JWT_SECRET: ""
  MAIL_USERNAME: "mail_user"
  MAIL_PASSWORD: ""
