apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-secrets
type: Opaque
stringData:
  APP_KEY: ""           # preencher antes do deploy
  DB_USERNAME: ""       # preencher antes do deploy
  DB_PASSWORD: ""       # preencher antes do deploy
  JWT_SECRET: ""        # preencher antes do deploy
  MAIL_USERNAME: ""     # AWS SES - preencher antes do deploy
  MAIL_PASSWORD: ""     # AWS SES - preencher antes do deploy
