apiVersion: v1
kind: Secret
metadata:
  name: oficina-mecanica-secrets
type: Opaque
stringData:
  APP_KEY: "base64:+r7C1wl3qTTsB7UIK1dpkYTS2IUFUlyztUlBYrkR32s="
  DB_USERNAME: "oficina_user"
  DB_PASSWORD: "oficina_pass"
  DB_DATABASE: "oficina_mecanica"
  JWT_SECRET: "Bmij6COI746ASY2Eaak6eMH3WAv7FqXGEA3eHOv8tcDuTr7G12aZxQeqL6mb7byK"
  MAIL_USERNAME: "mail_user"
  MAIL_PASSWORD: "mail_password"
